### PR TITLE
Fix flag colours and marked/suspended/buried colours not showing up

### LINKED ISSUE #38: All custom flag and card state colors displaying black in browse window
#### Problem description

*Regardless of the color selected, the flag icons and their corresponding flag "highlight" are black in browse.  The card state "swatch" has the same issue.  Problem seems to be limited to the browse window; colors display properly on main screen and during review.  It's occurring on both my desktop and laptop.

However, if using a default theme (Catppuccin, Nord, etc.) the card states and flag colors/highlights display properly in browse.

Attached screenshot is the result of attempting to change the red flag and "new" card state to a custom color.*

Screenshot 2024-09-15 at 3 19 31 PM

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

```
Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.5-arm64-arm-64bit
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

### PR DESCRIPTION
**Pull request by iamllama**
Closes #38

This fixes flag and marked/suspended/buried colours not showing up, by specially handling those cases and using ARGB hex instead of `rgba(...)`

### CODE REVIEW

**Comment by BlueGreenMagick** [comment]
Feels a bit hacky, but if it works, it works.

I think it'd be better to change `hex_with_alpha_to_argb()` function to check `if hex_color.startswith("#") and len(hex_color) == 9:`. Colors written as svg keywords (e.g. `lightblue`) should continue to work.

After the change, one downside is that colors written using `argb(x, x, x, x)` syntax will no longer work. But it's probably fine since I don't think anyone uses it anyway.

**Comment by iamllama** [comment]
Added the mentioned check and support for `rgba(...)`

> After the change, one downside is that colors written using argb(x, x, x, x) syntax will no longer work

Not sure what you mean by this. It never even worked to begin with, since `QColor` doesn't accept it and it isn't even part of the CSS standard, nor sass

**Comment by BlueGreenMagick** [comment]
LGTM!

I don't have access to its Ankiweb account, so you'll have to wait. I'm not sure who has it currently.

**Comment by iamllama** [comment]
`ACCENT_CARD` and `ACCENT_NOTE` also need to be included in `ARGB_ONLY_ENTRIES` too, unfortunately, but they're blocked by https://github.com/ankitects/anki/pull/3629

**Pull request merged**
